model:
  VitUnet:
    load_checkpoint: False
    patch_size: 
      - 15
      - 22
    embed_dim: 32
    depth: 4
    num_heads: 4
    alpha: 0
    concat_voronoi: True
    
    unet_in_channel: 8
    unet_out_channel: 4
    down_block_types: 
      - DownBlock2D
      - DownBlock2D
      - DownBlock2D
      - AttnDownBlock2D
    up_block_types:
      - AttnUpBlock2D
      - UpBlock2D
      - UpBlock2D
      - UpBlock2D
    block_out_channels:
      - 32
      - 64
      - 128
      - 256
    attention_head_dim: 4

  Unet:
    load_checkpoint: False
    unet_in_channel: 4
    unet_out_channel: 4
    down_block_types: 
      - DownBlock2D
      - DownBlock2D
      - DownBlock2D
      - AttnDownBlock2D
    up_block_types:
      - AttnUpBlock2D
      - UpBlock2D
      - UpBlock2D
      - UpBlock2D
    block_out_channels:
      - 32
      - 64
      - 128
      - 256
    attention_head_dim: 4

  diffusion:
    load_checkpoint: False
    unet_model:
      in_channels: 4
      out_channels: 4
      time_embedding_type: positional
      flip_sin_to_cos: True
      down_block_type: 
        - DownBlock2D
        - DownBlock2D
        - CrossAttnDownBlock2D
        - CrossAttnDownBlock2D
      up_block_type:
        - CrossAttnUpBlock2D
        - CrossAttnUpBlock2D
        - UpBlock2D
        - UpBlock2D
      block_out_channels:
        - 32
        - 64
        - 128
        - 256
      act_fn: silu
      cross_attention_dim: 256
      attention_head_dim: 4

    condition_encoder:
      patch_size: 
        - 15
        - 22
      in_chans: 4
      embed_dim: 256
      depth: 4
      num_heads: 4
      mlp_ratio: 3

learning_rate: 0.0001
lr_schedule: False
eta_min: 0.0001
t_max: 80
weight_decay: 0
batch_size: 32
epochs: 120
device: cuda

noise_scheduler:
  P_mean: 1.2
  P_std: 1.7

    
